services:
  gateway:
    image: ghcr.io/microservices-benchmarking-11-kiop-2023/csharp-mono:latest
    build:
      dockerfile: src/Pb.ApiGateway/Dockerfile
      context: .
    ports:
      - 5000:80
      